### ISSUE TITLE
dart toml support add or save to file?

### ISSUE THREAD

**Issue by luckrill** [just95/toml.dart#26]
can refer to python toml support tomlkit: https://pypi.org/project/tomlkit/

not found dart toml support add method and save to file method

**Comment by just95** [comment]
If I understand your question correctly, you are asking whether `toml.dart` supports the manipulation of TOML documents and saving manipulated documents to a file.

It is correct that there is no method for saving TOML documents. In the VM it would be straight forward to implement such a method using `dart:io` and the existing API to encode TOML documents.

```dart
import 'dart:io';
import 'package:toml/toml.dart';

extension on TomlDocument {
  Future<void> save(String filename) {
    return File(filename).writeAsString(toString());
  }
}
```

However, since I am not sure what the expected behavior of such a method would be on the web, I am probably not going to add this feature to the official API. Suggestions for how a `TomlDocument.save` method should behave on the web are welcome, though. Also keep in mind that `toml.dart` does not yet preserve comments and whitespace.

The manipulation of `TomlDocument`s is not directly supported either. In fact, the AST is an immutable data structure by design. However, you can convert TOML documents to a `Map`, manipulate the map and convert it back to a TOML document.

```dart
var config = TomlDocument.load('config.toml').toMap();
config['foo'] = 'bar';
var manipulated = TomlDocument.fromMap(config);
```

I am aware that this solution is not ideal. The code above will not only discard comments and whitespace, but may also rearrange key/value pairs, change the kind of string and number literals and never produces inline tables.
In the future I will add a new data structure that provides a higher level API for accessing and manipulating TOML documents.

**Comment by luckrill** [comment]
Encoding TOML

var manipulated = TomlDocument.fromMap(config).

save manipulated.toString() to file.

toml format content save to file succeed.
