### ISSUE TITLE
Support sync methods as well as async

### ISSUE THREAD

**Issue by dooley-ch** [just95/toml.dart#41]
As the title states, this library would be very useful to me if the author had consider the need to be able to use it in situations where you can't or don't want to use async methods e.g. load method.

**Comment by just95** [comment]
Hi, thanks for your feature request. As I understand, you ask for a `TomlDocument.loadSync` method that behaves like `TomlDocument.load` but returns a `TomlDocument` instead of a `Future<TomlDocument>`. On platforms with `dart:io` it would definitely be possible for me to implement such a method. However, I am currently unaware of any synchronous HTTP API that I could use to implement this method on the web. Would it be sufficient for you usecase if the method threw an exception if `dart:io` is not available?

**Comment by dooley-ch** [comment]
My main use is to store configuration information in console applications.  I have a config class and as part of it's initialisation I load the settings from a toml file.  And you can't use an async method in the constructor.  I'm not a web developer, so limited knowledge there, but I can't see a situation where one would try to perform the same action in any case, so I think it would be acceptable.

**Comment by just95** [comment]
I released the [new method](https://pub.dev/documentation/toml/0.14.0/toml/TomlDocument/loadSync.html) in version 0.14.0 of the package.

**Comment by dooley-ch** [comment]
Thanks, I will take a look at it tomorrow.

**Comment by dooley-ch** [comment]
Hi There,

Just to let you know, I tested the new version and it works perfectly for me.  Thanks.
